language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: iYLbNXW7ooR81bomL4lZ+EyOrgc8nApGr3DvWE4yVci4QLYlOhz6tVbpqC8ItA/zyxsdQACdfK0VIa0bWbLLCr1zcQd8KBLyxXnuLGeH96NP77gViNURod0IV3XocP/HolN1QhG7r17pHVFLwHT8XaQ24ELyah25Lr5uL/eH8/GNsl1phuxKyb/vsFjeoCZj8FY8ofWzfT+dLbGCkyohVS2PwNkameruT7NqQEIAsZH7ClxLkiiePNTVppXkdAPdOKtHXGWvaufwvB+n0KgmsOi3NxnUNQCGW9eTKrtaxC13HehiwDJB3B/7SUstjMBA5rZy2+dVNAanfQk+2RKQa4djxqN/Yy9tZlgXH+5zxBB6+mxPMvqs96m+YoIoB/x2sKxrhXiN8/Zy5+8Alpq81UWfj8ZNXgFobnoxQf5OuYoP1NpHbRLf8x7xsH4EaQ1F/06yHZF6yXuGz1rpGQlj3/7nD1lksK7ofpXExQarIpeSomvRmoyk4oEpNoOAtj41owOYbQw4ObaVGiHOotejUMi3l1zDodsuhOf+vEdNk47JtW0boJF3DsDueeTfp4F8lbwuZ9H8BPJ1u+WAW0aDPMc0XQFHsD534r+FpE6lu3g5YM+G/4aBlJ0fdf8G3qjPH4OEayfstWg53P22m7rO3zh2J8M78RadQv6+76BBzSI=
  on:
    tags: true
    branch: master
    repo: DEGJS/formValidation
